### PR TITLE
[Feature] Add width & height to media detail model

### PR DESCRIPTION
**Pull request by Dvergar**
This PR adds `width` & `height` to the model returned by the connector `detail` method. `MediaDetail` model is now diverging from `Media` (query method).

## Related tickets

https://chilipublishintranet.atlassian.net/browse/EDT-1054

### CODE REVIEW

**Comment by pietervp** [comment]
Also update https://github.com/chili-publish/studio-sdk/blob/main/types/MediaConnector.d.ts to reflect the same changes, would be good to review if the complete api surfacce still matches what we expect.

**Review by pietervp — CHANGES_REQUESTED** [review]
Also update https://github.com/chili-publish/studio-sdk/blob/main/types/MediaConnector.d.ts to reflect the same changes, would be good to review if the complete api surfacce still matches what we expect.

**Comment by Dvergar** [comment]
> Also update https://github.com/chili-publish/studio-sdk/blob/main/types/MediaConnector.d.ts to reflect the same changes, would be good to review if the complete api surfacce still matches what we expect.

Ooops, you mentioned it in chat and i completely overlooked that.

So I updated both media & font connectors, we do not have preview (font) in getcapabilities so this probably needs to be added as well but i'll prefer not to do it in this ticket.

Probably some more cleanup related to that will be done in scope of >> https://chilipublishintranet.atlassian.net/browse/EDT-1172

@evan-mcgeek May I have your eyes 👀 on the font connector side?

PS: I'll split again MediaCapabilities/FontCapabilities

**Comment by Dvergar** [comment]
Just adding some findings.

We do have 

```typescript
export enum MediaDownloadType {
    LowResolutionWeb = 'lowresWeb',
    HighResolutionWeb = 'highresWeb',
}
```

Was it an intended constraint to omit `outputVideo` & `outputPdf`?
Is it a standard for you WRS to start an enum entry with an uppercase?

**Review by evan-mcgeek — APPROVED** [review]
LGTM! The only thing left is to add a `preview` capability to the font connector

**Review by brapoprod — APPROVED** [review]
seems non-breaking to me

**Comment by pietervp** [comment]
> Just adding some findings.
> 
> We do have
> 
> ```ts
> export enum MediaDownloadType {
>     LowResolutionWeb = 'lowresWeb',
>     HighResolutionWeb = 'highresWeb',
> }
> ```
> 
> Was it an intended constraint to omit `outputVideo` & `outputPdf`? Is it a standard for you WRS to start an enum entry with an uppercase?

That was intentional, because WRS should only ever use one of those.

**Review by pietervp — APPROVED** [review]

**Pull request merged**
